### PR TITLE
Update to 1.20

### PR DESCRIPTION
**Pull request by ArtixBTW**
I've tested this and it works without any problems. I'm making the request from my 1.20 branch into your 1.19 branch since you don't have one for 1.20. (I'm guessing you can change that yourself).

~~Edit: `gradle runClient` works fine, but `gradle build` doesn't? It says something about not being able to validate the access widener, tbh I don't really know what that means, maybe you might?~~
Edit 2: I fixed it

### CODE REVIEW

**Comment by MCRusher** [comment]
I'm glad I looked at the prs, thanks for this. No one mod seems to do everything this one does.

And of course thanks to Cammie for creating the mod.

**Comment by Cm4nXD** [comment]
Where can I download your 1.20 version of the mod?

**Comment by MCRusher** [comment]
you have to clone the fork repo and use gradle to build it.

**Comment by ajaxnotmeta** [comment]
> you have to clone the fork repo and use gradle to build it.

how to use gradle? im new to this kind of java thing

**Comment by MCRusher** [comment]
1. make sure a java 17 jdk (Java Development Kit) is in the path. Either grab openjdk and add it to the path manually or just install regular Java jdk I guess.
2. clone this fork
3. download the fabric test mod template and overwrite this project's gradle folder with the one from the text mod, since the gradle folder from this project doesn't seem to work,
4. run `gradlew build` on the commandline
5. navigate to build/lib and grab the jar that doesn't say sources.

**Comment by Easton99** [comment]
What's holding this back from being merged?

**Comment by ajaxnotmeta** [comment]
> What's holding this back from being merged?

i have a feeling that Carmie is inactive is the reason
i cound be wrong though, and hopefully we see 1.20+ of this amazing mod

**Comment by venaminecraft** [comment]
Could you please provide a 1.20.2 build @ArchB1W? 😊

**Comment by venaminecraft** [comment]
@ajaxnotmeta Carmie's not modding anymore, you can find more information on the discord announcements channel.

I hope people can keep this mod up to date.

**Comment by ajaxnotmeta** [comment]
> @ajaxnotmeta Carmie's not modding anymore, you can find more information on the discord announcements channel.
> 
> I hope people can keep this mod up to date.

and i do hope someone can just take over and fork this mod, my comunity felt loss at this features that honestly make furnace minecart and railroad actually matters again and can compete well with ice boats and elytra with the disadvantage of it less speedy than the other 2 but completely hands free transportation

**Comment by venaminecraft** [comment]
Different mod but maybe it's helpful: 

https://modrinth.com/mod/audaki-cart-engine

**Comment by CammiePone** [comment]
honestly debating keeping this and Icarus up to date. some of my spark for modding was reignited recently, so i've been working on Arcanus: Continuum some

**Comment by vlad8599** [comment]
[crash-2023-12-22_19.32.37-client.txt](https://github.com/CammiePone/Cammies-Minecart-Tweaks/files/13754745/crash-2023-12-22_19.32.37-client.txt)

Mod dont work on 1.20.4, even with this update to 1.20.

How to fix? Please, tell me!

**Comment by Blugithubber** [comment]
> [crash-2023-12-22_19.32.37-client.txt](https://github.com/CammiePone/Cammies-Minecart-Tweaks/files/13754745/crash-2023-12-22_19.32.37-client.txt)
> 
> Mod dont work on 1.20.4, even with this update to 1.20.
> 
> How to fix? Please, tell me!

Have u managed to find a solution to this? Also looking to use this for 1.20.4

**Comment by vlad8599** [comment]
No...

**Comment by CammiePone** [comment]
yea lemme just finally take care of this after *checks notes* almost a year

**Pull request merged**
